RTL-377: add change streams for dynamic pricing
mongodb-industry-solutions/retail-store pull request #27
Opened 2024-11-12 19:54 UTC by AngelicaGE

Jira ticket: https://jira.mongodb.org/browse/RTL-377

Changes include
- Add change streams
- update pred price component
- add example .env file to include new vars needed for changestream

2024-11-12 19:55 UTC, AngelicaGE commented
https://github.com/user-attachments/assets/c90ac86e-0262-45b3-9ce2-7495af8f5352

2024-11-13 09:24 UTC, frankbaldi44 approved these changes
LGTM

2024-11-13 09:29 UTC, frankbaldi44 commented on EXAMPEL.env.local
Typo in name of file. Please update.

2024-11-13 09:53 UTC, frankbaldi44 requested changes
@AngelicaGE 

1. Please review filename typo
2. I've suggested some changes in the SSE/route.js
3. Let's test by running generator.py

2024-11-13 09:53 UTC, frankbaldi44 commented on app/api/sse/route.js
@AngelicaGE  Can we add error handling? 


```
changeStream.on('error', (error) => {
--
console.error('Change stream error:', error);
writer.close(); // Close the writer on error
});
```

2024-11-13 09:53 UTC, frankbaldi44 commented on app/api/sse/route.js
Hi @AngelicaGE looks good, but let's make it a bit more robust:

- Handle Change Stream Closure: Let's listen to the change stream if it get's unexpectedly closed re-establish connection.

- Implement a Retry Mechanism: Use a simple backoff strategy to retry connecting to the change stream after a certain interval if it fails.

- Graceful Shutdown: Ensure that when the server is shutting down, you clean up resources properly.

**My suggestion to test (run the generator.py file to test the whole system)**

````
import { getPredPriceChangeStream } from '@/app/_lib/mongodb';
--
import { NextResponse } from 'next/server';
 
const HEARTBEAT_INTERVAL = 5000; // Keep alive interval in milliseconds
const RETRY_INTERVAL = 1000; // Initial retry interval in milliseconds
 
let changeStream; // Global variable to hold the change stream
let retryTimeout; // Variable to hold the retry timeout
 
async function setupChangeStream(writer) {
try {
changeStream = await getPredPriceChangeStream();
 
changeStream.on('change', (change) => {
// Notify the client about the change
sendUpdate(change, writer);
});
 
changeStream.on('error', (error) => {
console.error('Change stream error:', error);
// Attempt to re-establish the change stream
retryChangeStream(writer);
});
 
changeStream.on('close', () => {
console.log('Change stream closed, attempting to reconnect...');
retryChangeStream(writer);
});
} catch (error) {
console.error('Error setting up change stream:', error);
retryChangeStream(writer);
}
}
 
function retryChangeStream(writer) {
if (retryTimeout) return; // Prevent multiple retries
 
retryTimeout = setTimeout(async () => {
console.log('Retrying to set up change stream...');
await setupChangeStream(writer);
retryTimeout = null; // Reset the timeout
}, RETRY_INTERVAL);
}
 
function sendUpdate(data, writer) {
if (writer.locked) {
const event = `data: ${JSON.stringify(data)}\n\n`;
writer.write(new TextEncoder().encode(event)).catch((error) => {
console.error('Error writing update:', error);
});
} else {
console.warn('Writable stream is not locked, skipping update.');
}
}
 
export async function GET(req) {
if (req.headers.get('accept') === 'text/event-stream') {
const { readable, writable } = new TransformStream();
const writer = writable.getWriter();
 
// Set SSE headers
const headers = new Headers({
'Content-Type': 'text/event-stream',
'Cache-Control': 'no-cache',
'Connection': 'keep-alive',
});
 
const intervalId = setInterval(() => {
if (writer.locked) {
writer.write(new TextEncoder().encode(': heartbeat\n\n')).catch((error) => {
console.error('Error writing heartbeat:', error);
});
}
}, HEARTBEAT_INTERVAL);
 
// Set up the change stream
await setupChangeStream(writer);
 
// Handle client disconnect
req.signal.addEventListener('abort', () => {
console.log("Client disconnected");
clearInterval(intervalId);
if (changeStream) {
changeStream.close(); // Close the change stream
}
writer.close().catch((error) => {
console.error('Error closing writer:', error);
});
});
 
return new NextResponse(readable, { headers });
} else {
console.log('404');
return new NextResponse('Not Found', { status: 404 });
}
}
 
// Graceful shutdown for the server
process.on('SIGINT', () => {
console.log('Shutting down gracefully...');
if (changeStream) {
changeStream.close(); // Close the change stream
}
process.exit(0);
});

2024-11-13 10:38 UTC, bereilhp commented on EXAMPEL.env.local
> +MONGODB_URI=
Why do we have two MongoDB connection URIs (`IST_SHARED_MONGODB` and `MONGODB_URI`)? Can we consolidate them into a single URI called `MONGODB_URI`?

2024-11-19 11:51 UTC, bereilhp approved these changes
LGTM!

2024-11-19 11:52 UTC, merged